pipeline {
    agent any
    stages {
        stage('upload') {
            steps {
                sh ''' env
                source /home/tibco/proveparam/config.txt
                cd $pathupload
   ./AppManage -upload -ear $fileear -app $app -domain $domain -user $user -pw $pswd
'''
            }
        }
        
    }
}
